In [1]:
import tensorflow as tf
print(('Your tensorflow version: {0}').format(tf.__version__))

Your tensorflow version: 2.16.1


In [3]:
#Create a constant tensor A
A=tf.constant([[4,3],[6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]])>

In [4]:
V = tf.Variable([[3,1],[5,2]])
B = tf.constant([[7,8],[3,2]])
print(V)
print(B)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]])>
tf.Tensor(
[[7 8]
 [3 2]], shape=(2, 2), dtype=int32)


In [7]:
AB_concatenated = tf.concat(values=[A,B],axis=0)
print(AB_concatenated)

tf.Tensor(
[[4 3]
 [6 1]
 [7 8]
 [3 2]], shape=(4, 2), dtype=int32)


In [8]:
AB_concatenated = tf.concat(values=[A,B],axis=1)
print(AB_concatenated)

tf.Tensor(
[[4 3 7 8]
 [6 1 3 2]], shape=(2, 4), dtype=int32)


In [13]:
tensor = tf.random.uniform(shape=[3,4],dtype=tf.float32)
print(tensor)

tf.Tensor(
[[0.19115138 0.7188443  0.54416716 0.40930057]
 [0.64810216 0.9450133  0.56455624 0.08061957]
 [0.899873   0.2111044  0.47391605 0.26456332]], shape=(3, 4), dtype=float32)


In [11]:
reshaped_tensor = tf.reshape(tensor=tensor, shape = [4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [14]:
#Typecast a tensor
tensor = tf.constant([[4.6,3.5],[2.3,6.2],[2.6,7.4]])
tensor_as_int = tf.cast(tensor,tf.int32)
print(tensor)
print(tensor_as_int)

tf.Tensor(
[[4.6 3.5]
 [2.3 6.2]
 [2.6 7.4]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[4 3]
 [2 6]
 [2 7]], shape=(3, 2), dtype=int32)


In [15]:
a=tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 2, 2],
       [3, 6, 7]])>

In [16]:
A=tf.constant([[4,3,],[3,9]])
v=tf.constant([[4],[3]])
Av=tf.matmul(A,v)
Av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[25],
       [39]])>

In [17]:
Av=tf.multiply(A,v)
Av

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 12],
       [ 9, 27]])>

In [18]:
A=tf.constant([[4,9],[5,6],[1,8]])
rows,columns = A.shape
print('rows:', rows, 'columns:', columns)
rows, columns = A.shape
A_identity = tf.eye(num_rows = rows,num_columns=columns,dtype = tf.int32)
A_identity

rows: 3 columns: 2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]])>